root: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 'latest'
    ecmaFeatures:
        jsx: true
    sourceType: module
plugins:
    - '@typescript-eslint'
    - 'prettier'
rules:
    no-shadow: 'off'
    no-use-before-define: 'off'
    comma-dangle:
        - 'error'
        - 'only-multiline'
    '@typescript-eslint/no-shadow': 'error'
    '@typescript-eslint/no-use-before-define': 'off'
    '@typescript-eslint/no-namespace': 'off'
    '@typescript-eslint/no-empty-interface': 'off'
    '@typescript-eslint/no-non-null-assertion': 'off'
ignorePatterns:
    - '**/*/node_modules'
    - '**/*/dist'
    - '**/*/build'
settings:
    'react':
        'version': 'detect'
